name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Run the workflow
      run: |
        set -e
        set -x
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        # Install Chromium dependencies needed for PDF printing
        sudo apt install libgbm1 -y
        # Run the command
        npm install
        node .
        # Add the command output to the commit
        git add *.pdf
        # Reset unstaged changes to prevent `git commit` from yelling if there's e.g. `package-lock.json` or caches
        git checkout -- .
        # Commit the added changes to the repository associated with this workflow (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Commit the changed PDF"
        # Rebase if the branch has meanwhile changed (fail if there are automatically irresolvable merge conflicts)
        git pull --rebase
        # Push the commit to the repository associated with this workflow
        git push
